services:
  napcat:
    image: mlikiowa/napcat-docker:latest
    container_name: napcat
    restart: on-failure
    network_mode: bridge

    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:3001:3001"
      - "127.0.0.1:6099:6099"

    environment:
      - NAPCAT_UID=${NAPCAT_UID}
      - NAPCAT_GID=${NAPCAT_GID}
      - NAPCAT_HEADLESS=true
      - ACCOUNT=3495972136
    volumes:
      - ./data/QQ:/app/.config/QQ
      - ./data/config:/app/napcat/config
      - ./data/plugins:/app/napcat/plugins

    extra_hosts:
      - "host.docker.internal:host-gateway"

    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"
